services:
  photonvision:
    build: .
    privileged: true
    restart: unless-stopped
    volumes:
      - .:/app
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 5800:5800
      - 1181:1181
      - 1182:1182
      - 1183:1183
      - 1184:1184
      - 1185:1185
      - 1186:1186
    working_dir: /app
    command: bash -c "chmod +x entrypoint.sh && ./entrypoint.sh"